version: '3.4'

services:
  tcc-sigo-normas-acl:
    image: tcc-sigo-normas-acl
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 44300:80
      - 44301:443